### ISSUE TITLE
Impossible de récupérer le contenu de mon Formulaire. 

### ISSUE THREAD

**Issue by FredMeziere** [FredMeziere/Portfolio#1]
Grace a Paul j'ai pu découvrir nodemailer, qui est un super moyen d'envoyer les données d'un formulaire à un mail, plus simple que mailjs.

Apres avoir suivi plusieurs tuto, j'arrive à m'envoyer un mail sur ma boite mail.

Le mail s'envoi bien sur ma boite mail mais il arrive vide. 

J'en déduis qu'il  n'arrive surement pas à prendre les informations contenues dans mon req.body car rien ne s'affiche dans mon console.log ou justement je lui demande de voir ce qu'il contient.

J'ai aussi 2 erreurs :

![image](https://user-images.githubusercontent.com/85186423/218104596-26c1fa11-2b59-414e-959e-91e451ed4662.png)

```
Uncaught TypeError: Cannot read properties of undefined (reading 'parentNode')
    at instana.js:17:9
    at instana.js:18:5
```
Sur la console du navigateur.

![image](https://user-images.githubusercontent.com/85186423/218104545-13a38544-8783-454e-93ab-2cdc2bfb670b.png)

Et une seconde erreur dans le terminal de vscode

![image](https://user-images.githubusercontent.com/85186423/218104860-01e58c92-d239-4815-9260-57b726ee6871.png)

J'ai bien sur chercher sur google en effectuant les démarche mais ça ne change rien. Je me demande si j'ai bien fait mes routes ou mes Controller ? 

Une fois le form envoyer sur ma boite mail, la page charge de façon infinie. Mais j'avoue être bloqué 

liens utiles : 

https://www.youtube.com/watch?v=30VeUWxZjS8&t=587s&ab_channel=ConorBailey
https://nodemailer.com/about/
https://www.youtube.com/watch?v=thAP7Fvrql4&ab_channel=Shilleh

**Comment by kevinhouguet** [comment]
Il fonction ton `console.log(formData);` dans ton fichier client.js ? c'est à ce moment que tu mets les infos dans ton formData donc peut-être que rien ne se met dedans et que tu as un problème là dessus.

**Comment by enzoclock** [comment]
@FredMeziere Hello !

Peux-tu : 
1) Nous copier le code où tu appelles l'API (= la fonction) de Nodemailer 
2) Vérifier la valeur des paramètres que tu passe à la fonction qui envoie le mail. 

De plus, 
de mémoire, le mail doit être envoyé côté backend. Et là tu nous link une erreur frontend. Donc tu as peut-être 2 erreurs qui se cumulent.

**Comment by FredMeziere** [comment]
@kevinhouguet  Exact il ne sort rien dedans :/ Mais je vois pas pk, car c'est comme ça que ça fonctionne :/

**Comment by FredMeziere** [comment]
Hello @enzoclock et merci d'avance pour l'aide ! 

Coté client : 

![image](https://user-images.githubusercontent.com/85186423/218113416-04c6ff96-1602-4921-b65b-376beba1e9ef.png)

Coté back :

      Controller : 

C'est ici ou je require nodemailer

![image](https://user-images.githubusercontent.com/85186423/218113609-bd7b0961-dbb5-45be-b8d4-aa82defcc0cb.png)

      Router : 

![image](https://user-images.githubusercontent.com/85186423/218113734-28911dad-f319-4698-a4b7-1b69ffa96be0.png)

Si il faut le code je le copie colle pas de soucis :) Je me tiens à votre disposition si vous avez des idées de mon soucis :)

**Comment by enzoclock** [comment]
- Pourquoi tu t'embêtes à utiliser `XMLHttpRequester` alors qu'on a `fetch` depuis 2015 😅 Utilise fetch ça simplifiera ton code.
- Tu as `console.log(req.body)` côté backend ? S'il y a rien dedans : 
  - tu as un body parser middleware en amont de ton controlleur ? 
  - l'appel à xhr n'est peut-être pas bon. L'occasion donc de refacto avec fetch.

Quand tu auras un bon body côté backend, LA on pourra faire des choses avec Nodemailer :)

**Comment by FredMeziere** [comment]
@enzoclock  J'ai suivi le tuto de Paul qui de son coté à marcher ! Mais je vais regarder avec `fetch` ! Merci 

Le console.log de req.body ne donne rien il est vide :/ !

Non pas de body parser juste router controller 

Je vais regarder tout ça merci à toi Enzo, je te tiens au courant de l'avancée :)

**Comment by enzoclock** [comment]
> on pas de body parser juste router controller

Faut look un petit recap S04 alors :D 

`app.use(express.json())` et/ou `express.urlencoded({ extended true })` était pas là juste pour rigoler :D

**Comment by FredMeziere** [comment]
@enzoclock  

Okay j'avais mal compris ahah 

![image](https://user-images.githubusercontent.com/85186423/218117082-5b81a608-2bed-4102-93e7-cc293d90f375.png)
 
 Dans mon index je les ai bien ^^ Je savais plus le terme ... Mais oui je fait mon portfolio pour justement revoir un peu tout

**Comment by enzoclock** [comment]
@FredMeziere Peut-être qu'il faut MULTER pour les FormData 🤔 Je sais pas trop, je pense pas. 
En tout cas en passant à FETCH peut-être que tu auras un body :D 🤞

**Comment by FredMeziere** [comment]
@enzoclock  Je vais regarder tout ça merci !! :)

**Comment by sandro971** [comment]
Hello.
Juste en passant, on ne peux pas faire de `addEventListener` directement sur un `document.getElementsByClassName('...')`
Cette dernière va renvoyer un Object, mais qui sera juste une collection de Nœuds ..
JS vanilla ne s'utilise pas comme JQuery 🐰

Préfère utiliser des libs comme `axios` ou tout simplement `fetch` plutôt que XHR 🐰
Pas sur que ça résout ton problème mais ça mange pas de pain 🐰 ( ou carotte )

**Comment by FredMeziere** [comment]
@kevinhouguet  @sandro971  @enzoclock  Alors c'était bien une erreur de ma part ! Et l'erreur était des plus bête ...

### **ROULEMENT DE TAMBOUR**.....

J'avais "Juste" pas link mon script JS... ça marche enfin !!

**Comment by enzoclock** [comment]
@FredMeziere Pile poil au moment du weekend ! Bien joué :D 
Bon weekend !

**Comment by kevinhouguet** [comment]
XD bravo @FredMeziere tu dormiras mieux ce soir :p

**Comment by FredMeziere** [comment]
@enzoclock  Ahaha ! 2 semaines j'ai plus de week-end je fais que coder mon portfolio car c'est trop satisfaisant d'enfin faire du concret ! Mais soulagé d'enfin avoir trouver mon erreur plus que discutable !!!

@kevinhouguet  oui ça fait 2-3 jours que je dors mal à cause de ce formulaire de la mort ! TOUT ça pour un script non link omg !!
